-- MySQL Script generated by MySQL Workbench
-- 02/24/16 21:42:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `sigla` VARCHAR(6) NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `salarioBase` FLOAT NOT NULL COMMENT '',
  PRIMARY KEY (`idCargo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `idEndereco` INT NOT NULL COMMENT '',
  `logradouro` VARCHAR(45) NULL COMMENT '',
  `descricao` VARCHAR(45) NULL COMMENT '',
  `numero` INT NULL COMMENT '',
  `cep` VARCHAR(11) NULL COMMENT '',
  PRIMARY KEY (`idEndereco`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `cpf` VARCHAR(13) NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `telefone` VARCHAR(11) NULL COMMENT '',
  `salario` FLOAT NOT NULL COMMENT '',
  `horario` VARCHAR(45) NULL COMMENT '',
  `filiacaoPai` VARCHAR(45) NOT NULL COMMENT '',
  `filiacaoMae` VARCHAR(45) NOT NULL COMMENT '',
  `idade` INT NOT NULL COMMENT '',
  `identidade` VARCHAR(45) NOT NULL COMMENT '',
  `nacionalidade` VARCHAR(45) NOT NULL COMMENT '',
  `Endereco_idEndereco` INT NOT NULL COMMENT '',
  `Cargo_idCargo1` INT NOT NULL COMMENT '',
  PRIMARY KEY (`cpf`)  COMMENT '',
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC)  COMMENT '',
  UNIQUE INDEX `identidade_UNIQUE` (`identidade` ASC)  COMMENT '',
  INDEX `fk_Funcionario_Endereco_idx` (`Endereco_idEndereco` ASC)  COMMENT '',
  INDEX `fk_Funcionario_Cargo2_idx` (`Cargo_idCargo1` ASC)  COMMENT '',
  CONSTRAINT `fk_Funcionario_Endereco`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `mydb`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Funcionario_Cargo2`
    FOREIGN KEY (`Cargo_idCargo1`)
    REFERENCES `mydb`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `idDepartamento` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `sigla` VARCHAR(45) NOT NULL COMMENT '',
  `numeroFuncionarios` INT NULL COMMENT '',
  `Funcionario_cpf` VARCHAR(13) NOT NULL COMMENT '',
  PRIMARY KEY (`idDepartamento`)  COMMENT '',
  INDEX `fk_Departamento_Funcionario1_idx` (`Funcionario_cpf` ASC)  COMMENT '',
  CONSTRAINT `fk_Departamento_Funcionario1`
    FOREIGN KEY (`Funcionario_cpf`)
    REFERENCES `mydb`.`Funcionario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dependentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dependentes` (
  `idDependentes` INT NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `idade` INT NOT NULL COMMENT '',
  `parentesco` VARCHAR(45) NOT NULL COMMENT '',
  `sexo` VARCHAR(45) NOT NULL COMMENT '',
  `Funcionario_cpf` VARCHAR(13) NOT NULL COMMENT '',
  PRIMARY KEY (`idDependentes`)  COMMENT '',
  INDEX `fk_Dependentes_Funcionario1_idx` (`Funcionario_cpf` ASC)  COMMENT '',
  CONSTRAINT `fk_Dependentes_Funcionario1`
    FOREIGN KEY (`Funcionario_cpf`)
    REFERENCES `mydb`.`Funcionario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
