-- MySQL Script generated by MySQL Workbench
-- 02/22/16 21:48:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema empresa_2015175
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa_2015175
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa_2015175` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `empresa_2015175` ;

-- -----------------------------------------------------
-- Table `empresa_2015175`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_2015175`.`Cliente` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `telefone` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `nascimento` DATE NOT NULL COMMENT '',
  `cpf` CHAR(14) NULL COMMENT '',
  `endereco` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '',
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_2015175`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_2015175`.`Produto` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_2015175`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_2015175`.`Venda` (
  `codigo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Cliente_codigo` INT NOT NULL COMMENT '',
  `Produto_codigo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`codigo`)  COMMENT '',
  INDEX `fk_Venda_Cliente_idx` (`Cliente_codigo` ASC)  COMMENT '',
  INDEX `fk_Venda_Produto1_idx` (`Produto_codigo` ASC)  COMMENT '',
  CONSTRAINT `fk_Venda_Cliente`
    FOREIGN KEY (`Cliente_codigo`)
    REFERENCES `empresa_2015175`.`Cliente` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Produto1`
    FOREIGN KEY (`Produto_codigo`)
    REFERENCES `empresa_2015175`.`Produto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
